title: Sec Bites
description: Practical cybersecurity knowledge, served in small bites.
url: "https://rahul0216.github.io"
baseurl: "/sec-bites"
lang: en
timezone: UTC

author:
  name: Sec Bites

repository: rahul0216/sec-bites

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs"
    values:
      layout: article

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-seo-tag
